"""empty message

Revision ID: 0e56a79cfd03
Revises: 5764bfa18d4f
Create Date: 2023-12-04 21:59:25.412430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e56a79cfd03'
down_revision = '5764bfa18d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
