"""empty message

Revision ID: 5764bfa18d4f
Revises: 65949cd6141e
Create Date: 2023-12-04 17:53:08.103552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5764bfa18d4f'
down_revision = '65949cd6141e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
