"""

Revision ID: b977d62cb0c9
Revises: ad2a93ed6a41
Create Date: 2023-12-01 09:44:18.214601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b977d62cb0c9'
down_revision = 'ad2a93ed6a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
